version: "2"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: "node:alpine"
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=local
      - JWT_KEY=secret
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: "npm start"